name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: patch
        run: |
          cd src

          ./check_verilog_timerconsts.sh || true

          echo "### Temporary patch remove before production and signoff"
          echo "### For local simulation these timers values are 1/200th or 1/25th of the normal wall-clock time"
          echo "### This patch restores the production values to meet USB specification with a 48MHz PHY clock source"

          ./check_verilog_timerconsts.sh patch quiet

          echo ""
          echo "### This now validates the values inside verilog are production system values or halts the CI"

          ./check_verilog_timerconsts.sh

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@tt04

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@tt04
