name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

    - name: patch
      run: |
        cd src
        cp UsbDeviceTop.v UsbDeviceTop.v.gds_orig
        # Temporary patch remove before production and signoff
        # For local simulation these timers values are 1/200th of the normal time
        # This patch restores the production values to meet USB specification
        sed -e "s#rx_timerLong_counter == 23'h0012a7#rx_timerLong_counter == 23'h0e933f#" -i UsbDeviceTop.v
        sed -e "s#rx_timerLong_counter == 23'h000947#rx_timerLong_counter == 23'h07403f#" -i UsbDeviceTop.v
        sed -e "s#rx_timerLong_counter == 23'h0002b7#rx_timerLong_counter == 23'h021fbf#" -i UsbDeviceTop.v
        diff -u UsbDeviceTop.v.gds_orig UsbDeviceTop.v

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@tt04

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@tt04
