name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: patch
        run: |
          cd src
          # Temporary patch remove before production and signoff
          # For local simulation these timers values are 1/200th of the normal time
          # This patch restores the production values to meet USB specification

          ./check_verilog_timerconsts.sh patch quiet
          # This now validates for production by default
          ./check_verilog_timerconsts.sh

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@tt04

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@tt04
