name: publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: [docs, gds, test, coverage]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: dlmiles/tt-gds-action/publish@tt04
