name: publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: [docs, gds, test, coverage]
    types:
      - completed

permissions:
  contents: read
  packages: read
  id-token: write
  pages: write

jobs:
  on-success:
    runs-on: ubuntu-latest
    
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: publish
        uses: dlmiles/tt-gds-action/publish@tt04
        with:
          # Need to explicitly pass as input.token into composite action
          token: ${{ secrets.GITHUB_TOKEN }}
